// Public shared run output page.
// Accessible by anyone with the run UUID — no auth required.
// The UUID is a 128-bit random value (unguessable), serving as the share token.

import { createAdminClient } from '@/lib/supabase/admin'
import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { RunShareView } from '@/components/runtime/run-share-view'

interface PageProps {
  params: Promise<{ runId: string }>
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { runId } = await params
  const db = createAdminClient()
  if (!db) return { title: 'Shared Output' }

  const { data } = await db
    .from('execution_logs')
    .select('agents(name)')
    .eq('id', runId)
    .single()

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const agentName = (data?.agents as any)?.name
  return {
    title: agentName ? `${agentName} — Output` : 'Shared Output',
    description: agentName ? `Result generated by the ${agentName} AI agent` : 'AI agent output',
  }
}

export default async function SharePage({ params }: PageProps) {
  const { runId } = await params
  const db = createAdminClient()
  if (!db) notFound()

  const { data: run } = await db
    .from('execution_logs')
    .select('id, status, input, output, started_at, completed_at, agents(id, name, description, deploy_slug, is_deployed)')
    .eq('id', runId)
    .single()

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const output = run?.output as any
  if (!run || !output?.result) notFound()

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const agent = run.agents as any

  return (
    <RunShareView
      runId={run.id}
      agentName={agent?.name ?? 'Agent Output'}
      agentDescription={agent?.description ?? null}
      agentSlug={agent?.is_deployed && agent?.deploy_slug ? agent.deploy_slug : null}
      result={output.result as string}
      completedAt={run.completed_at ?? null}
      toolCallsCount={output?.tool_calls_count ?? null}
    />
  )
}
