'use client'

import { useState } from 'react'
import { Sparkles, Clock, Zap, ExternalLink, Copy, Check } from 'lucide-react'
import { Markdown } from '@/components/ai-elements/markdown'

interface RunShareViewProps {
  runId: string
  agentName: string
  agentDescription: string | null
  agentSlug: string | null
  result: string
  completedAt: string | null
  toolCallsCount: number | null
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })
}

export function RunShareView({
  agentName,
  agentDescription,
  agentSlug,
  result,
  completedAt,
  toolCallsCount,
}: RunShareViewProps) {
  const [copied, setCopied] = useState(false)

  const handleCopy = async () => {
    await navigator.clipboard.writeText(window.location.href)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Top bar */}
      <header className="sticky top-0 z-10 border-b border-border bg-background/80 backdrop-blur-sm">
        <div className="mx-auto flex max-w-7xl items-center gap-3 px-6 py-3">
          <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-primary">
            <span className="text-xs font-bold text-primary-foreground">
              {agentName.charAt(0).toUpperCase()}
            </span>
          </div>
          <div className="min-w-0 flex-1">
            <span className="truncate text-sm font-semibold text-foreground">{agentName}</span>
            {agentDescription && (
              <span className="ml-2 text-xs text-muted-foreground hidden sm:inline">
                — {agentDescription}
              </span>
            )}
          </div>
          <div className="flex shrink-0 items-center gap-2">
            {agentSlug && (
              <a
                href={`/${agentSlug}`}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-1 rounded-md border border-border px-2.5 py-1 text-[11px] text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
              >
                <ExternalLink className="h-3 w-3" />
                Try agent
              </a>
            )}
            <button
              onClick={handleCopy}
              className="flex items-center gap-1 rounded-md border border-border px-2.5 py-1 text-[11px] text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
            >
              {copied ? (
                <>
                  <Check className="h-3 w-3 text-green-500" />
                  <span className="text-green-600">Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="h-3 w-3" />
                  Copy link
                </>
              )}
            </button>
          </div>
        </div>
      </header>

      {/* Output */}
      <main className="mx-auto max-w-7xl px-6 py-10">
        {/* Meta row */}
        <div className="mb-8 flex flex-wrap items-center gap-4 text-xs text-muted-foreground">
          {completedAt && (
            <span className="flex items-center gap-1.5">
              <Clock className="h-3 w-3" />
              {formatDate(completedAt)}
            </span>
          )}
          {toolCallsCount != null && toolCallsCount > 0 && (
            <span className="flex items-center gap-1.5">
              <Zap className="h-3 w-3" />
              {toolCallsCount} tool call{toolCallsCount !== 1 ? 's' : ''}
            </span>
          )}
          <span className="flex items-center gap-1.5">
            <Sparkles className="h-3 w-3" />
            Generated by {agentName}
          </span>
        </div>

        {/* Result content */}
        <div className="rounded-xl border border-border bg-card p-6 sm:p-8 shadow-sm">
          <Markdown>{result}</Markdown>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border py-6 mt-8">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6">
          <span className="text-xs text-muted-foreground">
            Powered by{' '}
            <a
              href="/"
              className="font-medium text-foreground hover:underline"
            >
              Terabits AI
            </a>
          </span>
          {agentSlug && (
            <a
              href={`/${agentSlug}`}
              className="flex items-center gap-1.5 text-xs text-muted-foreground transition-colors hover:text-foreground"
            >
              Run this agent yourself
              <ExternalLink className="h-3 w-3" />
            </a>
          )}
        </div>
      </footer>
    </div>
  )
}
